"""empty message

Revision ID: f34a32e9791f
Revises: 49b9fdb19218
Create Date: 2022-08-29 16:24:54.143468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34a32e9791f'
down_revision = '49b9fdb19218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorites_nature_id_key', 'favorites', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('favorites_nature_id_key', 'favorites', ['nature_id'])
    # ### end Alembic commands ###
